### ISSUE TITLE
windows 64-Bit compile error

### ISSUE THREAD

**Issue by laoqiuqiu** [TheLazyTomcat/Libs#1]
```
[dcc64 Error] BitOps.pas(4063): E2107 Operand size mismatch
[dcc64 Error] BitOps.pas(4190): E2107 Operand size mismatch
[dcc64 Error] BitOps.pas(4317): E2107 Operand size mismatch
```

**Comment by TheLazyTomcat** [comment]
Seems to be related to (or the same as) https://github.com/TheLazyTomcat/lib.BitOps/issues/1
I will correct it today.

**Comment by TheLazyTomcat** [comment]
Should be corrected now. If anything new arises, please post it to the issue mentioned above.
